In [1]:
import pandas as pd

In [2]:
stats = pd.read_csv("data/b_fpoints.csv", index_col = 0)
metrics = pd.read_csv("data/bmetrics24.csv")
metrics.head()

,"last_name, first_name",player_id,year,xwoba,xwobacon,xbacon,exit_velocity_avg,launch_angle_avg,barrel_batted_rate,hard_hit_percent,...,edge_percent,whiff_percent,swing_percent,pull_percent,straightaway_percent,opposite_percent,f_strike_percent,flyballs_percent,linedrives_percent,sprint_speed
0,"Hunter, Torii",116338,2015,0.290,0.325,0.286,88.5,10.8,5.0,34.9,...,42.3,23.1,53.4,34.7,40.6,24.5,64.0,22.6,20.9,26.5
1,"Ortiz, David",120074,2015,0.420,0.474,0.364,93.0,15.7,13.1,49.1,...,41.9,23.2,44.7,41.9,36.4,21.7,52.1,25.6,28.7,23.1
2,"Rodriguez, Alex",121347,2015,0.368,0.436,0.338,91.3,12.2,10.9,43.9,...,42.2,32.0,43.9,38.4,43.9,16.9,60.3,24.9,24.9,23.9
3,"Ramirez, Aramis",133380,2015,0.304,0.323,0.279,87.4,15.8,5.6,34.5,...,41.8,17.9,52.9,36.9,38.3,24.8,65.5,24.5,29.1,24.3
4,"Beltre, Adrian",134181,2015,0.360,0.380,0.333,89.5,12.6,5.5,40.4,...,42.6,16.8,48.1,35.3,41.4,23.3,61.9,18.4,31.6,26.4

In [3]:
stats.head()

,Name,year,age,K,BB,RBI,TB,SB,G,R,Fpoints,Fpoints_G
0,"Hunter, Torii",2015,39,105,35,81,213,2,139,67,293,2.107914
1,"Ortiz, David",2015,39,95,77,108,292,0,146,73,455,3.116438
2,"Rodriguez, Alex",2015,39,145,84,86,254,4,151,83,366,2.423841
3,"Ramirez, Aramis",2015,37,68,31,75,201,1,137,43,283,2.065693
4,"Beltre, Adrian",2015,36,65,41,83,257,1,143,83,400,2.797203

In [4]:
metrics = metrics.rename(columns = {'last_name, first_name':'Name'})
metrics = metrics.drop(columns = ['player_id'])
metrics['year'] = metrics['year'] + 1
metrics = metrics[metrics['year'] < 2024]
stats = stats[stats['year'] > 2015]

metrics.head()

,Name,year,xwoba,xwobacon,xbacon,exit_velocity_avg,launch_angle_avg,barrel_batted_rate,hard_hit_percent,avg_best_speed,...,edge_percent,whiff_percent,swing_percent,pull_percent,straightaway_percent,opposite_percent,f_strike_percent,flyballs_percent,linedrives_percent,sprint_speed
0,"Hunter, Torii",2016,0.290,0.325,0.286,88.5,10.8,5.0,34.9,98.563404,...,42.3,23.1,53.4,34.7,40.6,24.5,64.0,22.6,20.9,26.5
1,"Ortiz, David",2016,0.420,0.474,0.364,93.0,15.7,13.1,49.1,102.851133,...,41.9,23.2,44.7,41.9,36.4,21.7,52.1,25.6,28.7,23.1
2,"Rodriguez, Alex",2016,0.368,0.436,0.338,91.3,12.2,10.9,43.9,101.381141,...,42.2,32.0,43.9,38.4,43.9,16.9,60.3,24.9,24.9,23.9
3,"Ramirez, Aramis",2016,0.304,0.323,0.279,87.4,15.8,5.6,34.5,97.851256,...,41.8,17.9,52.9,36.9,38.3,24.8,65.5,24.5,29.1,24.3
4,"Beltre, Adrian",2016,0.360,0.380,0.333,89.5,12.6,5.5,40.4,99.252697,...,42.6,16.8,48.1,35.3,41.4,23.3,61.9,18.4,31.6,26.4

In [5]:
fpts = stats[['Name','Fpoints_G', 'year']]
fpts.head()

                Name  Fpoints_G  year
445     Ortiz, David   3.543046  2016
446  Rodriguez, Alex   1.215385  2016
447   Beltre, Adrian   3.137255  2016
448  Beltran, Carlos   2.543046  2016
449    Werth, Jayson   2.160839  2016

In [6]:
both = fpts.merge(metrics, on = ['Name', 'year'])
both.head()

,Name,Fpoints_G,year,xwoba,xwobacon,xbacon,exit_velocity_avg,launch_angle_avg,barrel_batted_rate,hard_hit_percent,...,edge_percent,whiff_percent,swing_percent,pull_percent,straightaway_percent,opposite_percent,f_strike_percent,flyballs_percent,linedrives_percent,sprint_speed
0,"Ortiz, David",3.543046,2016,0.420,0.474,0.364,93.0,15.7,13.1,49.1,...,41.9,23.2,44.7,41.9,36.4,21.7,52.1,25.6,28.7,23.1
1,"Rodriguez, Alex",1.215385,2016,0.368,0.436,0.338,91.3,12.2,10.9,43.9,...,42.2,32.0,43.9,38.4,43.9,16.9,60.3,24.9,24.9,23.9
2,"Beltre, Adrian",3.137255,2016,0.360,0.380,0.333,89.5,12.6,5.5,40.4,...,42.6,16.8,48.1,35.3,41.4,23.3,61.9,18.4,31.6,26.4
3,"Beltran, Carlos",2.543046,2016,0.346,0.381,0.334,90.6,15.6,5.8,41.9,...,43.5,18.1,45.4,40.6,38.3,19.3,57.3,26.6,28.1,25.6
4,"Werth, Jayson",2.160839,2016,0.331,0.384,0.324,90.0,15.3,7.9,40.7,...,42.7,24.2,37.9,33.6,33.6,32.8,57.7,23.3,31.2,26.0

In [7]:
both.to_csv("data/b_combined.csv")